approvals = 0
secs = 1000
jefeBaseUrl = "https://jefe.getpared.com/"
usernameField = 'email'
passwordField = "password"
loginButton = "/html/body/div/div/form/div/div/div/div[5]/button/div"
regionDropDown = "filter-container"
workHistoryTab = "//*[@id=\"app\"]/div/div[2]/div[2]/div/section/section/div/div[2]/div[1]/div[1]/button[2]/div/div"
workHistoryTableRows = "//*[@id=\"app\"]/div/div[2]/div[2]/div/section/section/div/div[2]/div[1]/div[3]/div[2]/div/div/div[2]/div/div[2]/table/tbody/tr"
workHistoryTableColumns = "//*[@id=\"app\"]/div/div[2]/div[2]/div/section/section/div/div[2]/div[1]/div[3]/div[2]/div/div/div[2]/div/div[2]/table/tbody/tr/td"

referencesTab = "//*[@id=\"app\"]/div/div[2]/div[2]/div/section/section/div/div[2]/div[1]/div[1]/button[3]/div/div"
referenceTableRows = "//*[@id=\"app\"]/div/div[2]/div[2]/div/section/section/div/div[2]/div[1]/div[3]/div[3]/div/div/div[2]/div/div[2]/table/tbody/tr"
referenceTableColumns = "//*[@id=\"app\"]/div/div[2]/div[2]/div/section/section/div/div[2]/div[1]/div[3]/div[3]/div/div/div[2]/div/div[2]/table/tbody/tr/td"
referenceRatings = "/html/body/div[2]/div/div[1]/div/div/div/div[3]/div[1]/div[2]/div[2]/div"
referenceSurvey = "/html/body/div[2]/div/div[1]/div/div/div/div[3]/div[1]/div[1]/div[2]/div"
referenceGood = "/html/body/div[2]/div/div[1]/div/div/div/div[4]/div[2]/div[1]/button"
referenceBad = "/html/body/div[2]/div/div[1]/div/div/div/div[4]/div[2]/div[3]/button"

desiredRolesTab = "/html/body/div[1]/div/div[2]/div[2]/div/section/section/div/div[2]/div[1]/div[1]/button[4]"
desiredRoles = "/html/body/div[1]/div/div[2]/div[2]/div/section/section/div/div[2]/div[1]/div[3]/div[4]/div/div/div[2]/div/div[2]/table/tbody/tr/td[1]/span"

matchAttributesTab = "/html/body/div/div/div[2]/div[2]/div/section/section/div/div[2]/div[1]/div[1]/button[5]"
matchAttributesTemplate = "/html/body/div/div/div[2]/div[2]/div/section/section/div/div[2]/div[1]/div[3]/div[5]/div/div/div[1]/div/div[2]/div[1]/button"
attributeTemplates = "/html/body/div[2]/div/div[1]/div/div/div[1]/div[1]/div/div[1]/div[1]"

baristaTemplate = "/html/body/div[3]/div/div/div/div[1]/span"
lineCookHigh = "/html/body/div[3]/div/div/div/div[2]/span"
lineCookMed = "/html/body/div[3]/div/div/div/div[3]/span"
lineCookLow = "/html/body/div[3]/div/div/div/div[4]/span"
prepCook = "/html/body/div[3]/div/div/div/div[5]/span"
lineDishMed = "/html/body/div[3]/div/div/div/div[6]/span"
dishPrep = "/html/body/div[3]/div/div/div/div[7]/span"
dishwasher = "/html/body/div[3]/div/div/div/div[8]/span"
cashier = "/html/body/div[3]/div/div/div/div[9]/span"
fohLow = "/html/body/div[3]/div/div/div/div[10]/span"
fohMed = "/html/body/div[3]/div/div/div/div[11]/span"
fohHigh = "/html/body/div[3]/div/div/div/div[12]/span"
eventServer = "/html/body/div[3]/div/div/div/div[13]/span"
pastryCook = "/html/body/div[3]/div/div/div/div[14]/span"
barback = "/html/body/div[3]/div/div/div/div[15]/span"
bartenderLow = "/html/body/div[3]/div/div/div/div[16]/span"
bartenderMed = "/html/body/div[3]/div/div/div/div[17]/span"
bartenderHigh = "/html/body/div[3]/div/div/div/div[18]/span"
busser = "/html/body/div[3]/div/div/div/div[19]/span"

submitAttribute = "/html/body/div[3]/div/div[1]/div/div/div[2]/button[2]"

attributeType = "//*[@name=\"type\"]/div[1]/button/div/svg"
skillLevel = "/html/body/div[4]/div/div/div/div[1]"
customRole = "/html/body/div[4]/div/div/div/div[2]"
fthMatch = "/html/body/div[4]/div/div/div/div[3]"
attributeKey = "//*[@name=\"key\"]/div[1]/button/div/svg"

editProfile = "/html/body/div/div/div[2]/div[2]/div/section/section/div/div[1]/div/div/div/section[1]/div/div[2]/div/button[1]"
pxApprove = "fthApproved"
editorSubmit = "/html/body/div[3]/div/div[1]/div/div/div[2]/button[2]/div/span"

proStatus = "/html/body/div/div/div[2]/div[2]/div/section/section/div/div[1]/div/div/div/section[2]/div/div[1]/div[3]/div[2]/div/div"

optionsDropDown = "/html/body/div/div/div[2]/div[2]/div/section/section/div/div[1]/div/div/div/section[1]/div/div[2]/div/button[2]"
matchToShifts = "/html/body/div[3]/div/div/div/div/div/div[6]/span/div/div/div"

archivePro = "/html/body/div[3]/div/div/div/div/div/div[3]/span/div/div/div"
needsReferences = "/html/body/div[4]/div/div/div/div[6]/span/div/div/div"
submitArchive = "/html/body/div[3]/div/div[1]/div/div/div[2]/button[2]"

# Archival reasons after approval
fourteenDaySuspension = "/html/body/div[3]/div/div/div/div[1]/span"
sixtyDaySuspension = "/html/body/div[3]/div/div/div/div[2]/span"
sevenDaySuspension = "/html/body/div[3]/div/div/div/div[3]/span"
altercationDuringShift = "/html/body/div[3]/div/div/div/div[4]/span"
drugAlcoholDuringShift = "/html/body/div[3]/div/div/div/div[5]/span"
duplicate = "/html/body/div[3]/div/div/div/div[6]/span"
invalidPhoneNumber = "/html/body/div[3]/div/div/div/div[7]/span"
misrepresentation = "/html/body/div[3]/div/div/div/div[8]/span"
noCallNoShow = "/html/body/div[3]/div/div/div/div[9]/span"
profilePictureUpdate = "/html/body/div[3]/div/div/div/div[10]/span"
sexualHarassment = "/html/body/div[3]/div/div/div/div[11]/span"
theftOrDestruction = "/html/body/div[3]/div/div/div/div[12]/span"
tooManyBadReviews = "/html/body/div[3]/div/div/div/div[13]/span"
tooManyCancellations = "/html/body/div[3]/div/div/div/div[14]/span"
tooManyTardies = "/html/body/div[3]/div/div/div/div[15]/span"
tardiesAndCancellations = "/html/body/div[3]/div/div/div/div[16]/span"
unresponsive = "/html/body/div[3]/div/div/div/div[17]/span"
wageTheft = "/html/body/div[3]/div/div/div/div[18]/span"
walkOff = "/html/body/div[3]/div/div/div/div[19]/span"